---
- name: dev machines provisioned
  hosts: dev
  become: yes
  vars:
    maven_major_version: 3
    maven_version: 3.8.6
    java_jdk_version: java-11-openjdk-devel

  tasks:
  # install utilities
  - name: install package
    yum:
      name:
      - git
      - zsh
      - nano

  # install java
  - name: install jdk
    yum:
      name: "{{java_jdk_version}}"
      state: latest
      update_cache: yes

  - name: Set JAVA_HOME
    lineinfile:
      dest: /etc/environment
      state: present
      regexp: '^JAVA_HOME'
      line: 'JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk'

  # install maven
  - name: install maven
    unarchive:
      src: https://dlcdn.apache.org/maven/maven-{{maven_major_version}}/{{maven_version}}/binaries/apache-maven-{{maven_version}}-bin.tar.gz
      remote_src: yes
      dest: /opt/
      validate_certs: no 
#  - name: maven.sh
#    copy:
#      src: files/maven.sh
#      dest: /etc/profile.d/maven.sh
#      mode: '755'
  - name: Set MAVEN_HOME
    become: true
    lineinfile:
      dest: /etc/profile.d/maven.sh
      create: yes
      state: present
      mode: '0744'
      line: "{{ item }}"
    with_items:
    - "export M2_HOME=/opt/apache-maven-{{maven_version}}"
    - "export MAVEN_HOME=/opt/apache-maven-{{maven_version}}"
    - "export PATH=${M2_HOME}/bin:${PATH}"
