---
- name: staging server configured
  hosts: staging
  become: yes
  tasks:
  - name: docker installed
    include_tasks: docker-tasks_prof.yml

  - name: add vagrant user to docker group
    user:
      name: vagrant
      groups: docker
      append: yes
